[2m2022-04-08 15:22:28.510[0;39m [[32m INFO[0;39m] [35m15600[0;39m [2m[           main ][0;39m [32mnet.mingsoft.MSApplication[0;39m:55 [2m:[0;39m Starting MSApplication on yb with PID 15600 (D:\aa\MCMS-master\MCMS-master\target\classes started by Administrator in D:\aa\MCMS-master\MCMS-master)
[2m2022-04-08 15:22:28.520[0;39m [[32m INFO[0;39m] [35m19432[0;39m [2m[           main ][0;39m [32mnet.mingsoft.MSApplication[0;39m:55 [2m:[0;39m Starting MSApplication on yb with PID 19432 (D:\aa\MCMS-master\MCMS-master\target\classes started by Administrator in D:\aa\MCMS-master\MCMS-master)
[2m2022-04-08 15:22:28.845[0;39m [[32m INFO[0;39m] [35m15600[0;39m [2m[           main ][0;39m [32mnet.mingsoft.MSApplication[0;39m:652 [2m:[0;39m The following profiles are active: dev
[2m2022-04-08 15:22:29.041[0;39m [[32m INFO[0;39m] [35m19432[0;39m [2m[           main ][0;39m [32mnet.mingsoft.MSApplication[0;39m:652 [2m:[0;39m The following profiles are active: dev
[2m2022-04-08 15:22:53.014[0;39m [[32m INFO[0;39m] [35m15600[0;39m [2m[           main ][0;39m [32mcom.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure[0;39m:56 [2m:[0;39m Init DruidDataSource
[2m2022-04-08 15:22:53.015[0;39m [[32m INFO[0;39m] [35m19432[0;39m [2m[           main ][0;39m [32mcom.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure[0;39m:56 [2m:[0;39m Init DruidDataSource
[2m2022-04-08 15:22:54.330[0;39m [[32m INFO[0;39m] [35m19432[0;39m [2m[           main ][0;39m [32mcom.alibaba.druid.pool.DruidDataSource[0;39m:998 [2m:[0;39m {dataSource-1} inited
[2m2022-04-08 15:22:54.331[0;39m [[32m INFO[0;39m] [35m15600[0;39m [2m[           main ][0;39m [32mcom.alibaba.druid.pool.DruidDataSource[0;39m:998 [2m:[0;39m {dataSource-1} inited
[2m2022-04-08 15:22:56.292[0;39m [[33m WARN[0;39m] [35m15600[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.basic.dao.IManagerDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:22:56.304[0;39m [[33m WARN[0;39m] [35m19432[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.basic.dao.IManagerDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:22:56.421[0;39m [[33m WARN[0;39m] [35m15600[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.basic.dao.IModelDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:22:56.438[0;39m [[33m WARN[0;39m] [35m19432[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.basic.dao.IModelDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:22:56.485[0;39m [[33m WARN[0;39m] [35m15600[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.metadata.TableInfoHelper[0;39m:307 [2m:[0;39m Can not find table primary key in Class: "net.mingsoft.basic.entity.RoleModelEntity".
[2m2022-04-08 15:22:56.505[0;39m [[33m WARN[0;39m] [35m19432[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.metadata.TableInfoHelper[0;39m:307 [2m:[0;39m Can not find table primary key in Class: "net.mingsoft.basic.entity.RoleModelEntity".
[2m2022-04-08 15:23:00.839[0;39m [[32m INFO[0;39m] [35m15600[0;39m [2m[           main ][0;39m [32morg.apache.coyote.http11.Http11NioProtocol[0;39m:173 [2m:[0;39m Initializing ProtocolHandler ["http-nio-8080"]
[2m2022-04-08 15:23:00.839[0;39m [[32m INFO[0;39m] [35m19432[0;39m [2m[           main ][0;39m [32morg.apache.coyote.http11.Http11NioProtocol[0;39m:173 [2m:[0;39m Initializing ProtocolHandler ["http-nio-8080"]
[2m2022-04-08 15:23:00.840[0;39m [[32m INFO[0;39m] [35m15600[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.StandardService[0;39m:173 [2m:[0;39m Starting service [Tomcat]
[2m2022-04-08 15:23:00.840[0;39m [[32m INFO[0;39m] [35m19432[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.StandardService[0;39m:173 [2m:[0;39m Starting service [Tomcat]
[2m2022-04-08 15:23:00.841[0;39m [[32m INFO[0;39m] [35m15600[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.StandardEngine[0;39m:173 [2m:[0;39m Starting Servlet engine: [Apache Tomcat/9.0.46]
[2m2022-04-08 15:23:00.841[0;39m [[32m INFO[0;39m] [35m19432[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.StandardEngine[0;39m:173 [2m:[0;39m Starting Servlet engine: [Apache Tomcat/9.0.46]
[2m2022-04-08 15:23:00.869[0;39m [[32m INFO[0;39m] [35m15600[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.AprLifecycleListener[0;39m:173 [2m:[0;39m Loaded Apache Tomcat Native library [1.2.31] using APR version [1.7.0].
[2m2022-04-08 15:23:00.869[0;39m [[32m INFO[0;39m] [35m15600[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.AprLifecycleListener[0;39m:173 [2m:[0;39m APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
[2m2022-04-08 15:23:00.871[0;39m [[32m INFO[0;39m] [35m15600[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.AprLifecycleListener[0;39m:173 [2m:[0;39m APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
[2m2022-04-08 15:23:00.872[0;39m [[32m INFO[0;39m] [35m19432[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.AprLifecycleListener[0;39m:173 [2m:[0;39m Loaded Apache Tomcat Native library [1.2.31] using APR version [1.7.0].
[2m2022-04-08 15:23:00.873[0;39m [[32m INFO[0;39m] [35m19432[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.AprLifecycleListener[0;39m:173 [2m:[0;39m APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
[2m2022-04-08 15:23:00.874[0;39m [[32m INFO[0;39m] [35m19432[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.AprLifecycleListener[0;39m:173 [2m:[0;39m APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
[2m2022-04-08 15:23:00.970[0;39m [[32m INFO[0;39m] [35m15600[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.AprLifecycleListener[0;39m:173 [2m:[0;39m OpenSSL successfully initialized [OpenSSL 1.1.1l  24 Aug 2021]
[2m2022-04-08 15:23:00.969[0;39m [[32m INFO[0;39m] [35m19432[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.AprLifecycleListener[0;39m:173 [2m:[0;39m OpenSSL successfully initialized [OpenSSL 1.1.1l  24 Aug 2021]
[2m2022-04-08 15:23:01.559[0;39m [[32m INFO[0;39m] [35m15600[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/][0;39m:173 [2m:[0;39m Initializing Spring embedded WebApplicationContext
[2m2022-04-08 15:23:01.559[0;39m [[32m INFO[0;39m] [35m19432[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/][0;39m:173 [2m:[0;39m Initializing Spring embedded WebApplicationContext
[2m2022-04-08 15:23:02.523[0;39m [[33m WARN[0;39m] [35m15600[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.cms.dao.ICategoryDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:23:02.552[0;39m [[33m WARN[0;39m] [35m19432[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.cms.dao.ICategoryDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:23:02.629[0;39m [[33m WARN[0;39m] [35m15600[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.cms.dao.IContentDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:23:02.657[0;39m [[33m WARN[0;39m] [35m19432[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.cms.dao.IContentDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:23:03.141[0;39m [[33m WARN[0;39m] [35m15600[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.mdiy.dao.IModelDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:23:03.144[0;39m [[33m WARN[0;39m] [35m19432[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.mdiy.dao.IModelDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:23:04.096[0;39m [[33m WARN[0;39m] [35m15600[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.toolkit.ReflectionKit[0;39m:107 [2m:[0;39m Warn: HistoryLogBizImpl's superclass not ParameterizedType
[2m2022-04-08 15:23:04.097[0;39m [[33m WARN[0;39m] [35m15600[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.toolkit.ReflectionKit[0;39m:107 [2m:[0;39m Warn: HistoryLogBizImpl's superclass not ParameterizedType
[2m2022-04-08 15:23:04.160[0;39m [[33m WARN[0;39m] [35m19432[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.toolkit.ReflectionKit[0;39m:107 [2m:[0;39m Warn: HistoryLogBizImpl's superclass not ParameterizedType
[2m2022-04-08 15:23:04.160[0;39m [[33m WARN[0;39m] [35m19432[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.toolkit.ReflectionKit[0;39m:107 [2m:[0;39m Warn: HistoryLogBizImpl's superclass not ParameterizedType
[2m2022-04-08 15:23:04.406[0;39m [[33m WARN[0;39m] [35m15600[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.mdiy.dao.IPageDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:23:04.489[0;39m [[33m WARN[0;39m] [35m19432[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.mdiy.dao.IPageDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:23:05.574[0;39m [[32m INFO[0;39m] [35m15600[0;39m [2m[           main ][0;39m [32mcom.alibaba.druid.pool.DruidDataSource[0;39m:2071 [2m:[0;39m {dataSource-1} closing ...
[2m2022-04-08 15:23:05.576[0;39m [[32m INFO[0;39m] [35m15600[0;39m [2m[           main ][0;39m [32mcom.alibaba.druid.pool.DruidDataSource[0;39m:2144 [2m:[0;39m {dataSource-1} closed
[2m2022-04-08 15:23:05.582[0;39m [[32m INFO[0;39m] [35m15600[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.StandardService[0;39m:173 [2m:[0;39m Stopping service [Tomcat]
[2m2022-04-08 15:23:05.738[0;39m [[33m WARN[0;39m] [35m19432[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.basic.dao.ILogDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:23:06.061[0;39m [[33m WARN[0;39m] [35m19432[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.toolkit.ReflectionKit[0;39m:107 [2m:[0;39m Warn: CityBizImpl's superclass not ParameterizedType
[2m2022-04-08 15:23:06.061[0;39m [[33m WARN[0;39m] [35m19432[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.toolkit.ReflectionKit[0;39m:107 [2m:[0;39m Warn: CityBizImpl's superclass not ParameterizedType
[2m2022-04-08 15:23:06.332[0;39m [[33m WARN[0;39m] [35m19432[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.basic.dao.IRoleDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:23:06.980[0;39m [[33m WARN[0;39m] [35m19432[0;39m [2m[           main ][0;39m [33mnet.sf.ehcache.config.ConfigurationFactory[0;39m:136 [2m:[0;39m No configuration found. Configuring ehcache from ehcache-failsafe.xml  found in the classpath: jar:file:/D:/2022/maven_repos/net/sf/ehcache/ehcache/2.10.9.2/ehcache-2.10.9.2.jar!/ehcache-failsafe.xml
[2m2022-04-08 15:23:08.567[0;39m [[33m WARN[0;39m] [35m19432[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.mdiy.dao.ITagDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:23:08.985[0;39m [[33m WARN[0;39m] [35m19432[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.toolkit.ReflectionKit[0;39m:107 [2m:[0;39m Warn: ModelDataImpl's superclass not ParameterizedType
[2m2022-04-08 15:23:08.985[0;39m [[33m WARN[0;39m] [35m19432[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.toolkit.ReflectionKit[0;39m:107 [2m:[0;39m Warn: ModelDataImpl's superclass not ParameterizedType
[2m2022-04-08 15:23:09.273[0;39m [[33m WARN[0;39m] [35m19432[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.mdiy.dao.IDictDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:23:17.496[0;39m [[32m INFO[0;39m] [35m19432[0;39m [2m[           main ][0;39m [32morg.quartz.impl.StdSchedulerFactory[0;39m:1220 [2m:[0;39m Using default implementation for ThreadExecutor
[2m2022-04-08 15:23:17.576[0;39m [[32m INFO[0;39m] [35m19432[0;39m [2m[           main ][0;39m [32morg.quartz.core.SchedulerSignalerImpl[0;39m:61 [2m:[0;39m Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
[2m2022-04-08 15:23:17.576[0;39m [[32m INFO[0;39m] [35m19432[0;39m [2m[           main ][0;39m [32morg.quartz.core.QuartzScheduler[0;39m:229 [2m:[0;39m Quartz Scheduler v.2.3.2 created.
[2m2022-04-08 15:23:17.577[0;39m [[32m INFO[0;39m] [35m19432[0;39m [2m[           main ][0;39m [32morg.quartz.simpl.RAMJobStore[0;39m:155 [2m:[0;39m RAMJobStore initialized.
[2m2022-04-08 15:23:17.579[0;39m [[32m INFO[0;39m] [35m19432[0;39m [2m[           main ][0;39m [32morg.quartz.core.QuartzScheduler[0;39m:294 [2m:[0;39m Scheduler meta-data: Quartz Scheduler (v2.3.2) 'quartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

[2m2022-04-08 15:23:17.579[0;39m [[32m INFO[0;39m] [35m19432[0;39m [2m[           main ][0;39m [32morg.quartz.impl.StdSchedulerFactory[0;39m:1374 [2m:[0;39m Quartz scheduler 'quartzScheduler' initialized from an externally provided properties instance.
[2m2022-04-08 15:23:17.579[0;39m [[32m INFO[0;39m] [35m19432[0;39m [2m[           main ][0;39m [32morg.quartz.impl.StdSchedulerFactory[0;39m:1378 [2m:[0;39m Quartz scheduler version: 2.3.2
[2m2022-04-08 15:23:17.580[0;39m [[32m INFO[0;39m] [35m19432[0;39m [2m[           main ][0;39m [32morg.quartz.core.QuartzScheduler[0;39m:2293 [2m:[0;39m JobFactory set to: org.springframework.scheduling.quartz.SpringBeanJobFactory@38816a6c
[2m2022-04-08 15:23:17.883[0;39m [[32m INFO[0;39m] [35m19432[0;39m [2m[           main ][0;39m [32morg.apache.coyote.http11.Http11NioProtocol[0;39m:173 [2m:[0;39m Starting ProtocolHandler ["http-nio-8080"]
[2m2022-04-08 15:23:17.906[0;39m [[32m INFO[0;39m] [35m19432[0;39m [2m[           main ][0;39m [32morg.quartz.core.QuartzScheduler[0;39m:547 [2m:[0;39m Scheduler quartzScheduler_$_NON_CLUSTERED started.
[2m2022-04-08 15:23:17.923[0;39m [[32m INFO[0;39m] [35m19432[0;39m [2m[           main ][0;39m [32mnet.mingsoft.MSApplication[0;39m:61 [2m:[0;39m Started MSApplication in 52.867 seconds (JVM running for 66.316)
[2m2022-04-08 15:24:29.548[0;39m [[32m INFO[0;39m] [35m19432[0;39m [2m[nio-8080-exec-2 ][0;39m [32morg.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/][0;39m:173 [2m:[0;39m Initializing Spring DispatcherServlet 'dispatcherServlet'
[2m2022-04-08 15:24:37.475[0;39m [[31mERROR[0;39m] [35m19432[0;39m [2m[eate-1013700132 ][0;39m [31mcom.alibaba.druid.pool.DruidDataSource[0;39m:2840 [2m:[0;39m create connection SQLException, url: jdbc:mysql://localhost:3306/mcms?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:903) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1657) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1723) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2838) [druid-1.2.8.jar:1.2.8]
Caused by: com.mysql.cj.exceptions.CJException: Unknown database 'mcms'
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:797) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:719) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:687) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:136) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:460) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:210) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1353) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:847) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	... 7 more

[2m2022-04-08 15:24:41.842[0;39m [[31mERROR[0;39m] [35m19432[0;39m [2m[eate-1013700132 ][0;39m [31mcom.alibaba.druid.pool.DruidDataSource[0;39m:2840 [2m:[0;39m create connection SQLException, url: jdbc:mysql://localhost:3306/mcms?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:903) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1657) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1723) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2838) [druid-1.2.8.jar:1.2.8]
Caused by: com.mysql.cj.exceptions.CJException: Unknown database 'mcms'
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:797) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:719) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:687) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:136) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:460) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:210) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1353) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:847) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	... 7 more

[2m2022-04-08 15:24:41.859[0;39m [[32m INFO[0;39m] [35m19432[0;39m [2m[eate-1013700132 ][0;39m [32mcom.alibaba.druid.pool.DruidAbstractDataSource[0;39m:1804 [2m:[0;39m {dataSource-1} failContinuous is true
[2m2022-04-08 15:24:46.742[0;39m [[31mERROR[0;39m] [35m19432[0;39m [2m[eate-1013700132 ][0;39m [31mcom.alibaba.druid.pool.DruidDataSource[0;39m:2840 [2m:[0;39m create connection SQLException, url: jdbc:mysql://localhost:3306/mcms?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:903) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1657) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1723) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2838) [druid-1.2.8.jar:1.2.8]
Caused by: com.mysql.cj.exceptions.CJException: Unknown database 'mcms'
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:797) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:719) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:687) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:136) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:460) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:210) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1353) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:847) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	... 7 more

[2m2022-04-08 15:24:51.513[0;39m [[31mERROR[0;39m] [35m19432[0;39m [2m[eate-1013700132 ][0;39m [31mcom.alibaba.druid.pool.DruidDataSource[0;39m:2840 [2m:[0;39m create connection SQLException, url: jdbc:mysql://localhost:3306/mcms?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:903) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1657) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1723) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2838) [druid-1.2.8.jar:1.2.8]
Caused by: com.mysql.cj.exceptions.CJException: Unknown database 'mcms'
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:797) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:719) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:687) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:136) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:460) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:210) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1353) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:847) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	... 7 more

[2m2022-04-08 15:24:56.390[0;39m [[31mERROR[0;39m] [35m19432[0;39m [2m[eate-1013700132 ][0;39m [31mcom.alibaba.druid.pool.DruidDataSource[0;39m:2840 [2m:[0;39m create connection SQLException, url: jdbc:mysql://localhost:3306/mcms?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:903) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1657) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1723) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2838) [druid-1.2.8.jar:1.2.8]
Caused by: com.mysql.cj.exceptions.CJException: Unknown database 'mcms'
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:797) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:719) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:687) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:136) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:460) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:210) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1353) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:847) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	... 7 more

[2m2022-04-08 15:25:01.186[0;39m [[31mERROR[0;39m] [35m19432[0;39m [2m[eate-1013700132 ][0;39m [31mcom.alibaba.druid.pool.DruidDataSource[0;39m:2840 [2m:[0;39m create connection SQLException, url: jdbc:mysql://localhost:3306/mcms?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:903) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1657) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1723) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2838) [druid-1.2.8.jar:1.2.8]
Caused by: com.mysql.cj.exceptions.CJException: Unknown database 'mcms'
	at jdk.internal.reflect.GeneratedConstructorAccessor93.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:797) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:719) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:687) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:136) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:460) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:210) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1353) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:847) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	... 7 more

[2m2022-04-08 15:25:05.941[0;39m [[31mERROR[0;39m] [35m19432[0;39m [2m[eate-1013700132 ][0;39m [31mcom.alibaba.druid.pool.DruidDataSource[0;39m:2840 [2m:[0;39m create connection SQLException, url: jdbc:mysql://localhost:3306/mcms?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:903) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1657) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1723) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2838) [druid-1.2.8.jar:1.2.8]
Caused by: com.mysql.cj.exceptions.CJException: Unknown database 'mcms'
	at jdk.internal.reflect.GeneratedConstructorAccessor93.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:797) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:719) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:687) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:136) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:460) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:210) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1353) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:847) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	... 7 more

[2m2022-04-08 15:25:10.720[0;39m [[31mERROR[0;39m] [35m19432[0;39m [2m[eate-1013700132 ][0;39m [31mcom.alibaba.druid.pool.DruidDataSource[0;39m:2840 [2m:[0;39m create connection SQLException, url: jdbc:mysql://localhost:3306/mcms?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:903) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1657) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1723) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2838) [druid-1.2.8.jar:1.2.8]
Caused by: com.mysql.cj.exceptions.CJException: Unknown database 'mcms'
	at jdk.internal.reflect.GeneratedConstructorAccessor93.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:797) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:719) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:687) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:136) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:460) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:210) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1353) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:847) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	... 7 more

[2m2022-04-08 15:25:15.614[0;39m [[31mERROR[0;39m] [35m19432[0;39m [2m[eate-1013700132 ][0;39m [31mcom.alibaba.druid.pool.DruidDataSource[0;39m:2840 [2m:[0;39m create connection SQLException, url: jdbc:mysql://localhost:3306/mcms?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:903) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1657) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1723) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2838) [druid-1.2.8.jar:1.2.8]
Caused by: com.mysql.cj.exceptions.CJException: Unknown database 'mcms'
	at jdk.internal.reflect.GeneratedConstructorAccessor93.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:797) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:719) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:687) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:136) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:460) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:210) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1353) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:847) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	... 7 more

[2m2022-04-08 15:25:20.374[0;39m [[31mERROR[0;39m] [35m19432[0;39m [2m[eate-1013700132 ][0;39m [31mcom.alibaba.druid.pool.DruidDataSource[0;39m:2840 [2m:[0;39m create connection SQLException, url: jdbc:mysql://localhost:3306/mcms?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:903) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1657) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1723) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2838) [druid-1.2.8.jar:1.2.8]
Caused by: com.mysql.cj.exceptions.CJException: Unknown database 'mcms'
	at jdk.internal.reflect.GeneratedConstructorAccessor93.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:797) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:719) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:687) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:136) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:460) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:210) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1353) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:847) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	... 7 more

[2m2022-04-08 15:25:25.294[0;39m [[31mERROR[0;39m] [35m19432[0;39m [2m[eate-1013700132 ][0;39m [31mcom.alibaba.druid.pool.DruidDataSource[0;39m:2840 [2m:[0;39m create connection SQLException, url: jdbc:mysql://localhost:3306/mcms?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:903) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1657) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1723) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2838) [druid-1.2.8.jar:1.2.8]
Caused by: com.mysql.cj.exceptions.CJException: Unknown database 'mcms'
	at jdk.internal.reflect.GeneratedConstructorAccessor93.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:797) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:719) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:687) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:136) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:460) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:210) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1353) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:847) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	... 7 more

[2m2022-04-08 15:25:30.317[0;39m [[31mERROR[0;39m] [35m19432[0;39m [2m[eate-1013700132 ][0;39m [31mcom.alibaba.druid.pool.DruidDataSource[0;39m:2840 [2m:[0;39m create connection SQLException, url: jdbc:mysql://localhost:3306/mcms?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:903) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1657) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1723) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2838) [druid-1.2.8.jar:1.2.8]
Caused by: com.mysql.cj.exceptions.CJException: Unknown database 'mcms'
	at jdk.internal.reflect.GeneratedConstructorAccessor93.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:797) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:719) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:687) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:136) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:460) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:210) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1353) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:847) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	... 7 more

[2m2022-04-08 15:25:35.230[0;39m [[31mERROR[0;39m] [35m19432[0;39m [2m[eate-1013700132 ][0;39m [31mcom.alibaba.druid.pool.DruidDataSource[0;39m:2840 [2m:[0;39m create connection SQLException, url: jdbc:mysql://localhost:3306/mcms?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:903) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1657) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1723) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2838) [druid-1.2.8.jar:1.2.8]
Caused by: com.mysql.cj.exceptions.CJException: Unknown database 'mcms'
	at jdk.internal.reflect.GeneratedConstructorAccessor93.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:797) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:719) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:687) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:136) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:460) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:210) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1353) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:847) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	... 7 more

[2m2022-04-08 15:25:40.002[0;39m [[31mERROR[0;39m] [35m19432[0;39m [2m[eate-1013700132 ][0;39m [31mcom.alibaba.druid.pool.DruidDataSource[0;39m:2840 [2m:[0;39m create connection SQLException, url: jdbc:mysql://localhost:3306/mcms?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:903) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1657) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1723) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2838) [druid-1.2.8.jar:1.2.8]
Caused by: com.mysql.cj.exceptions.CJException: Unknown database 'mcms'
	at jdk.internal.reflect.GeneratedConstructorAccessor93.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:797) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:719) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:687) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:136) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:460) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:210) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1353) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:847) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	... 7 more

[2m2022-04-08 15:25:44.777[0;39m [[31mERROR[0;39m] [35m19432[0;39m [2m[eate-1013700132 ][0;39m [31mcom.alibaba.druid.pool.DruidDataSource[0;39m:2840 [2m:[0;39m create connection SQLException, url: jdbc:mysql://localhost:3306/mcms?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:903) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1657) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1723) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2838) [druid-1.2.8.jar:1.2.8]
Caused by: com.mysql.cj.exceptions.CJException: Unknown database 'mcms'
	at jdk.internal.reflect.GeneratedConstructorAccessor93.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:797) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:719) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:687) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:136) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:460) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:210) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1353) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:847) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	... 7 more

[2m2022-04-08 15:25:49.534[0;39m [[31mERROR[0;39m] [35m19432[0;39m [2m[eate-1013700132 ][0;39m [31mcom.alibaba.druid.pool.DruidDataSource[0;39m:2840 [2m:[0;39m create connection SQLException, url: jdbc:mysql://localhost:3306/mcms?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:903) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1657) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1723) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2838) [druid-1.2.8.jar:1.2.8]
Caused by: com.mysql.cj.exceptions.CJException: Unknown database 'mcms'
	at jdk.internal.reflect.GeneratedConstructorAccessor93.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:797) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:719) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:687) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:136) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:460) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:210) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1353) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:847) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	... 7 more

[2m2022-04-08 15:25:54.284[0;39m [[31mERROR[0;39m] [35m19432[0;39m [2m[eate-1013700132 ][0;39m [31mcom.alibaba.druid.pool.DruidDataSource[0;39m:2840 [2m:[0;39m create connection SQLException, url: jdbc:mysql://localhost:3306/mcms?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:903) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1657) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1723) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2838) [druid-1.2.8.jar:1.2.8]
Caused by: com.mysql.cj.exceptions.CJException: Unknown database 'mcms'
	at jdk.internal.reflect.GeneratedConstructorAccessor93.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:797) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:719) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:687) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:136) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:460) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:210) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1353) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:847) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	... 7 more

[2m2022-04-08 15:25:59.035[0;39m [[31mERROR[0;39m] [35m19432[0;39m [2m[eate-1013700132 ][0;39m [31mcom.alibaba.druid.pool.DruidDataSource[0;39m:2840 [2m:[0;39m create connection SQLException, url: jdbc:mysql://localhost:3306/mcms?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:903) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1657) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1723) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2838) [druid-1.2.8.jar:1.2.8]
Caused by: com.mysql.cj.exceptions.CJException: Unknown database 'mcms'
	at jdk.internal.reflect.GeneratedConstructorAccessor93.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:797) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:719) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:687) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:136) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:460) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:210) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1353) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:847) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	... 7 more

[2m2022-04-08 15:26:03.829[0;39m [[31mERROR[0;39m] [35m19432[0;39m [2m[eate-1013700132 ][0;39m [31mcom.alibaba.druid.pool.DruidDataSource[0;39m:2840 [2m:[0;39m create connection SQLException, url: jdbc:mysql://localhost:3306/mcms?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:903) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1657) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1723) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2838) [druid-1.2.8.jar:1.2.8]
Caused by: com.mysql.cj.exceptions.CJException: Unknown database 'mcms'
	at jdk.internal.reflect.GeneratedConstructorAccessor93.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:797) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:719) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:687) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:136) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:460) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:210) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1353) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:847) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	... 7 more

[2m2022-04-08 15:26:08.575[0;39m [[31mERROR[0;39m] [35m19432[0;39m [2m[eate-1013700132 ][0;39m [31mcom.alibaba.druid.pool.DruidDataSource[0;39m:2840 [2m:[0;39m create connection SQLException, url: jdbc:mysql://localhost:3306/mcms?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:903) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1657) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1723) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2838) [druid-1.2.8.jar:1.2.8]
Caused by: com.mysql.cj.exceptions.CJException: Unknown database 'mcms'
	at jdk.internal.reflect.GeneratedConstructorAccessor93.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:797) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:719) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:687) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:136) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:460) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:210) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1353) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:847) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	... 7 more

[2m2022-04-08 15:26:13.344[0;39m [[31mERROR[0;39m] [35m19432[0;39m [2m[eate-1013700132 ][0;39m [31mcom.alibaba.druid.pool.DruidDataSource[0;39m:2840 [2m:[0;39m create connection SQLException, url: jdbc:mysql://localhost:3306/mcms?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:903) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1657) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1723) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2838) [druid-1.2.8.jar:1.2.8]
Caused by: com.mysql.cj.exceptions.CJException: Unknown database 'mcms'
	at jdk.internal.reflect.GeneratedConstructorAccessor93.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:797) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:719) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:687) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:136) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:460) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:210) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1353) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:847) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	... 7 more

[2m2022-04-08 15:26:18.104[0;39m [[31mERROR[0;39m] [35m19432[0;39m [2m[eate-1013700132 ][0;39m [31mcom.alibaba.druid.pool.DruidDataSource[0;39m:2840 [2m:[0;39m create connection SQLException, url: jdbc:mysql://localhost:3306/mcms?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:903) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1657) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1723) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2838) [druid-1.2.8.jar:1.2.8]
Caused by: com.mysql.cj.exceptions.CJException: Unknown database 'mcms'
	at jdk.internal.reflect.GeneratedConstructorAccessor93.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:797) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:719) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:687) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:136) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:460) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:210) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1353) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:847) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	... 7 more

[2m2022-04-08 15:26:22.947[0;39m [[31mERROR[0;39m] [35m19432[0;39m [2m[eate-1013700132 ][0;39m [31mcom.alibaba.druid.pool.DruidDataSource[0;39m:2840 [2m:[0;39m create connection SQLException, url: jdbc:mysql://localhost:3306/mcms?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:903) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1657) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1723) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2838) [druid-1.2.8.jar:1.2.8]
Caused by: com.mysql.cj.exceptions.CJException: Unknown database 'mcms'
	at jdk.internal.reflect.GeneratedConstructorAccessor93.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:797) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:719) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:687) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:136) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:460) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:210) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1353) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:847) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	... 7 more

[2m2022-04-08 15:26:27.680[0;39m [[31mERROR[0;39m] [35m19432[0;39m [2m[eate-1013700132 ][0;39m [31mcom.alibaba.druid.pool.DruidDataSource[0;39m:2840 [2m:[0;39m create connection SQLException, url: jdbc:mysql://localhost:3306/mcms?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:903) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1657) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1723) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2838) [druid-1.2.8.jar:1.2.8]
Caused by: com.mysql.cj.exceptions.CJException: Unknown database 'mcms'
	at jdk.internal.reflect.GeneratedConstructorAccessor93.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:797) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:719) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:687) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:136) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:460) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:210) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1353) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:847) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	... 7 more

[2m2022-04-08 15:26:32.433[0;39m [[31mERROR[0;39m] [35m19432[0;39m [2m[eate-1013700132 ][0;39m [31mcom.alibaba.druid.pool.DruidDataSource[0;39m:2840 [2m:[0;39m create connection SQLException, url: jdbc:mysql://localhost:3306/mcms?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:903) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1657) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1723) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2838) [druid-1.2.8.jar:1.2.8]
Caused by: com.mysql.cj.exceptions.CJException: Unknown database 'mcms'
	at jdk.internal.reflect.GeneratedConstructorAccessor93.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:797) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:719) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:687) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:136) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:460) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:210) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1353) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:847) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	... 7 more

[2m2022-04-08 15:26:37.233[0;39m [[31mERROR[0;39m] [35m19432[0;39m [2m[eate-1013700132 ][0;39m [31mcom.alibaba.druid.pool.DruidDataSource[0;39m:2840 [2m:[0;39m create connection SQLException, url: jdbc:mysql://localhost:3306/mcms?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&allowMultiQueries=true&useSSL=true, errorCode 0, state 08001

java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:110) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:97) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:89) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:63) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:73) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:903) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:828) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:453) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:246) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1657) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidAbstractDataSource.createPhysicalConnection(DruidAbstractDataSource.java:1723) ~[druid-1.2.8.jar:1.2.8]
	at com.alibaba.druid.pool.DruidDataSource$CreateConnectionThread.run(DruidDataSource.java:2838) [druid-1.2.8.jar:1.2.8]
Caused by: com.mysql.cj.exceptions.CJException: Unknown database 'mcms'
	at jdk.internal.reflect.GeneratedConstructorAccessor93.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:129) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:797) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:719) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:687) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:136) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:460) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:210) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1353) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.NativeSession.connect(NativeSession.java:157) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:847) ~[mysql-connector-java-8.0.25.jar:8.0.25]
	... 7 more

[2m2022-04-08 15:26:40.057[0;39m [[32m INFO[0;39m] [35m19432[0;39m [2m[eate-1013700132 ][0;39m [32mcom.alibaba.druid.pool.DruidAbstractDataSource[0;39m:1809 [2m:[0;39m {dataSource-1} failContinuous is false
[2m2022-04-08 15:28:46.818[0;39m [[32m INFO[0;39m] [35m13740[0;39m [2m[           main ][0;39m [32mnet.mingsoft.MSApplication[0;39m:55 [2m:[0;39m Starting MSApplication on yb with PID 13740 (D:\aa\MCMS-master\MCMS-master\target\classes started by Administrator in D:\aa\MCMS-master\MCMS-master)
[2m2022-04-08 15:28:46.829[0;39m [[32m INFO[0;39m] [35m13740[0;39m [2m[           main ][0;39m [32mnet.mingsoft.MSApplication[0;39m:652 [2m:[0;39m The following profiles are active: dev
[2m2022-04-08 15:28:49.190[0;39m [[32m INFO[0;39m] [35m13740[0;39m [2m[           main ][0;39m [32mcom.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure[0;39m:56 [2m:[0;39m Init DruidDataSource
[2m2022-04-08 15:28:49.330[0;39m [[32m INFO[0;39m] [35m13740[0;39m [2m[           main ][0;39m [32mcom.alibaba.druid.pool.DruidDataSource[0;39m:998 [2m:[0;39m {dataSource-1} inited
[2m2022-04-08 15:28:50.189[0;39m [[33m WARN[0;39m] [35m13740[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.basic.dao.IManagerDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:28:50.268[0;39m [[33m WARN[0;39m] [35m13740[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.basic.dao.IModelDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:28:50.323[0;39m [[33m WARN[0;39m] [35m13740[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.metadata.TableInfoHelper[0;39m:307 [2m:[0;39m Can not find table primary key in Class: "net.mingsoft.basic.entity.RoleModelEntity".
[2m2022-04-08 15:28:51.031[0;39m [[32m INFO[0;39m] [35m13740[0;39m [2m[           main ][0;39m [32morg.apache.coyote.http11.Http11NioProtocol[0;39m:173 [2m:[0;39m Initializing ProtocolHandler ["http-nio-8080"]
[2m2022-04-08 15:28:51.032[0;39m [[32m INFO[0;39m] [35m13740[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.StandardService[0;39m:173 [2m:[0;39m Starting service [Tomcat]
[2m2022-04-08 15:28:51.032[0;39m [[32m INFO[0;39m] [35m13740[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.StandardEngine[0;39m:173 [2m:[0;39m Starting Servlet engine: [Apache Tomcat/9.0.46]
[2m2022-04-08 15:28:51.034[0;39m [[32m INFO[0;39m] [35m13740[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.AprLifecycleListener[0;39m:173 [2m:[0;39m Loaded Apache Tomcat Native library [1.2.31] using APR version [1.7.0].
[2m2022-04-08 15:28:51.035[0;39m [[32m INFO[0;39m] [35m13740[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.AprLifecycleListener[0;39m:173 [2m:[0;39m APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
[2m2022-04-08 15:28:51.035[0;39m [[32m INFO[0;39m] [35m13740[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.AprLifecycleListener[0;39m:173 [2m:[0;39m APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
[2m2022-04-08 15:28:51.039[0;39m [[32m INFO[0;39m] [35m13740[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.AprLifecycleListener[0;39m:173 [2m:[0;39m OpenSSL successfully initialized [OpenSSL 1.1.1l  24 Aug 2021]
[2m2022-04-08 15:28:51.195[0;39m [[32m INFO[0;39m] [35m13740[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/][0;39m:173 [2m:[0;39m Initializing Spring embedded WebApplicationContext
[2m2022-04-08 15:28:51.699[0;39m [[33m WARN[0;39m] [35m13740[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.cms.dao.ICategoryDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:28:51.763[0;39m [[33m WARN[0;39m] [35m13740[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.cms.dao.IContentDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:28:52.070[0;39m [[33m WARN[0;39m] [35m13740[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.mdiy.dao.IModelDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:28:52.745[0;39m [[33m WARN[0;39m] [35m13740[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.toolkit.ReflectionKit[0;39m:107 [2m:[0;39m Warn: HistoryLogBizImpl's superclass not ParameterizedType
[2m2022-04-08 15:28:52.745[0;39m [[33m WARN[0;39m] [35m13740[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.toolkit.ReflectionKit[0;39m:107 [2m:[0;39m Warn: HistoryLogBizImpl's superclass not ParameterizedType
[2m2022-04-08 15:28:53.002[0;39m [[33m WARN[0;39m] [35m13740[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.mdiy.dao.IPageDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:28:53.556[0;39m [[33m WARN[0;39m] [35m13740[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.basic.dao.ILogDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:28:53.789[0;39m [[33m WARN[0;39m] [35m13740[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.toolkit.ReflectionKit[0;39m:107 [2m:[0;39m Warn: CityBizImpl's superclass not ParameterizedType
[2m2022-04-08 15:28:53.789[0;39m [[33m WARN[0;39m] [35m13740[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.toolkit.ReflectionKit[0;39m:107 [2m:[0;39m Warn: CityBizImpl's superclass not ParameterizedType
[2m2022-04-08 15:28:54.004[0;39m [[33m WARN[0;39m] [35m13740[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.basic.dao.IRoleDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:28:54.371[0;39m [[33m WARN[0;39m] [35m13740[0;39m [2m[           main ][0;39m [33mnet.sf.ehcache.config.ConfigurationFactory[0;39m:136 [2m:[0;39m No configuration found. Configuring ehcache from ehcache-failsafe.xml  found in the classpath: jar:file:/D:/2022/maven_repos/net/sf/ehcache/ehcache/2.10.9.2/ehcache-2.10.9.2.jar!/ehcache-failsafe.xml
[2m2022-04-08 15:28:54.505[0;39m [[33m WARN[0;39m] [35m13740[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.mdiy.dao.ITagDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:28:54.712[0;39m [[33m WARN[0;39m] [35m13740[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.toolkit.ReflectionKit[0;39m:107 [2m:[0;39m Warn: ModelDataImpl's superclass not ParameterizedType
[2m2022-04-08 15:28:54.713[0;39m [[33m WARN[0;39m] [35m13740[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.toolkit.ReflectionKit[0;39m:107 [2m:[0;39m Warn: ModelDataImpl's superclass not ParameterizedType
[2m2022-04-08 15:28:54.939[0;39m [[33m WARN[0;39m] [35m13740[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.mdiy.dao.IDictDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:28:58.481[0;39m [[32m INFO[0;39m] [35m13740[0;39m [2m[           main ][0;39m [32morg.quartz.impl.StdSchedulerFactory[0;39m:1220 [2m:[0;39m Using default implementation for ThreadExecutor
[2m2022-04-08 15:28:58.494[0;39m [[32m INFO[0;39m] [35m13740[0;39m [2m[           main ][0;39m [32morg.quartz.core.SchedulerSignalerImpl[0;39m:61 [2m:[0;39m Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
[2m2022-04-08 15:28:58.494[0;39m [[32m INFO[0;39m] [35m13740[0;39m [2m[           main ][0;39m [32morg.quartz.core.QuartzScheduler[0;39m:229 [2m:[0;39m Quartz Scheduler v.2.3.2 created.
[2m2022-04-08 15:28:58.495[0;39m [[32m INFO[0;39m] [35m13740[0;39m [2m[           main ][0;39m [32morg.quartz.simpl.RAMJobStore[0;39m:155 [2m:[0;39m RAMJobStore initialized.
[2m2022-04-08 15:28:58.496[0;39m [[32m INFO[0;39m] [35m13740[0;39m [2m[           main ][0;39m [32morg.quartz.core.QuartzScheduler[0;39m:294 [2m:[0;39m Scheduler meta-data: Quartz Scheduler (v2.3.2) 'quartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

[2m2022-04-08 15:28:58.496[0;39m [[32m INFO[0;39m] [35m13740[0;39m [2m[           main ][0;39m [32morg.quartz.impl.StdSchedulerFactory[0;39m:1374 [2m:[0;39m Quartz scheduler 'quartzScheduler' initialized from an externally provided properties instance.
[2m2022-04-08 15:28:58.496[0;39m [[32m INFO[0;39m] [35m13740[0;39m [2m[           main ][0;39m [32morg.quartz.impl.StdSchedulerFactory[0;39m:1378 [2m:[0;39m Quartz scheduler version: 2.3.2
[2m2022-04-08 15:28:58.496[0;39m [[32m INFO[0;39m] [35m13740[0;39m [2m[           main ][0;39m [32morg.quartz.core.QuartzScheduler[0;39m:2293 [2m:[0;39m JobFactory set to: org.springframework.scheduling.quartz.SpringBeanJobFactory@27f43664
[2m2022-04-08 15:28:58.675[0;39m [[32m INFO[0;39m] [35m13740[0;39m [2m[           main ][0;39m [32morg.apache.coyote.http11.Http11NioProtocol[0;39m:173 [2m:[0;39m Starting ProtocolHandler ["http-nio-8080"]
[2m2022-04-08 15:28:58.696[0;39m [[32m INFO[0;39m] [35m13740[0;39m [2m[           main ][0;39m [32morg.quartz.core.QuartzScheduler[0;39m:547 [2m:[0;39m Scheduler quartzScheduler_$_NON_CLUSTERED started.
[2m2022-04-08 15:28:58.710[0;39m [[32m INFO[0;39m] [35m13740[0;39m [2m[           main ][0;39m [32mnet.mingsoft.MSApplication[0;39m:61 [2m:[0;39m Started MSApplication in 12.482 seconds (JVM running for 14.758)
[2m2022-04-08 15:29:18.873[0;39m [[32m INFO[0;39m] [35m13740[0;39m [2m[nio-8080-exec-1 ][0;39m [32morg.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/][0;39m:173 [2m:[0;39m Initializing Spring DispatcherServlet 'dispatcherServlet'
[2m2022-04-08 15:31:59.041[0;39m [[32m INFO[0;39m] [35m2344[0;39m [2m[           main ][0;39m [32mnet.mingsoft.MSApplication[0;39m:55 [2m:[0;39m Starting MSApplication on yb with PID 2344 (D:\aa\MCMS-master\MCMS-master\target\classes started by Administrator in D:\aa\MCMS-master\MCMS-master)
[2m2022-04-08 15:31:59.053[0;39m [[32m INFO[0;39m] [35m2344[0;39m [2m[           main ][0;39m [32mnet.mingsoft.MSApplication[0;39m:652 [2m:[0;39m The following profiles are active: dev
[2m2022-04-08 15:32:01.461[0;39m [[32m INFO[0;39m] [35m2344[0;39m [2m[           main ][0;39m [32mcom.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure[0;39m:56 [2m:[0;39m Init DruidDataSource
[2m2022-04-08 15:32:01.578[0;39m [[32m INFO[0;39m] [35m2344[0;39m [2m[           main ][0;39m [32mcom.alibaba.druid.pool.DruidDataSource[0;39m:998 [2m:[0;39m {dataSource-1} inited
[2m2022-04-08 15:32:02.419[0;39m [[33m WARN[0;39m] [35m2344[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.basic.dao.IManagerDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:32:02.514[0;39m [[33m WARN[0;39m] [35m2344[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.basic.dao.IModelDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:32:02.562[0;39m [[33m WARN[0;39m] [35m2344[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.metadata.TableInfoHelper[0;39m:307 [2m:[0;39m Can not find table primary key in Class: "net.mingsoft.basic.entity.RoleModelEntity".
[2m2022-04-08 15:32:03.256[0;39m [[32m INFO[0;39m] [35m2344[0;39m [2m[           main ][0;39m [32morg.apache.coyote.http11.Http11NioProtocol[0;39m:173 [2m:[0;39m Initializing ProtocolHandler ["http-nio-8080"]
[2m2022-04-08 15:32:03.257[0;39m [[32m INFO[0;39m] [35m2344[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.StandardService[0;39m:173 [2m:[0;39m Starting service [Tomcat]
[2m2022-04-08 15:32:03.257[0;39m [[32m INFO[0;39m] [35m2344[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.StandardEngine[0;39m:173 [2m:[0;39m Starting Servlet engine: [Apache Tomcat/9.0.46]
[2m2022-04-08 15:32:03.259[0;39m [[32m INFO[0;39m] [35m2344[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.AprLifecycleListener[0;39m:173 [2m:[0;39m Loaded Apache Tomcat Native library [1.2.31] using APR version [1.7.0].
[2m2022-04-08 15:32:03.260[0;39m [[32m INFO[0;39m] [35m2344[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.AprLifecycleListener[0;39m:173 [2m:[0;39m APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
[2m2022-04-08 15:32:03.260[0;39m [[32m INFO[0;39m] [35m2344[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.AprLifecycleListener[0;39m:173 [2m:[0;39m APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
[2m2022-04-08 15:32:03.264[0;39m [[32m INFO[0;39m] [35m2344[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.AprLifecycleListener[0;39m:173 [2m:[0;39m OpenSSL successfully initialized [OpenSSL 1.1.1l  24 Aug 2021]
[2m2022-04-08 15:32:03.425[0;39m [[32m INFO[0;39m] [35m2344[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/][0;39m:173 [2m:[0;39m Initializing Spring embedded WebApplicationContext
[2m2022-04-08 15:32:03.900[0;39m [[33m WARN[0;39m] [35m2344[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.cms.dao.ICategoryDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:32:03.974[0;39m [[33m WARN[0;39m] [35m2344[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.cms.dao.IContentDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:32:04.267[0;39m [[33m WARN[0;39m] [35m2344[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.mdiy.dao.IModelDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:32:04.893[0;39m [[33m WARN[0;39m] [35m2344[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.toolkit.ReflectionKit[0;39m:107 [2m:[0;39m Warn: HistoryLogBizImpl's superclass not ParameterizedType
[2m2022-04-08 15:32:04.893[0;39m [[33m WARN[0;39m] [35m2344[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.toolkit.ReflectionKit[0;39m:107 [2m:[0;39m Warn: HistoryLogBizImpl's superclass not ParameterizedType
[2m2022-04-08 15:32:05.148[0;39m [[33m WARN[0;39m] [35m2344[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.mdiy.dao.IPageDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:32:05.673[0;39m [[33m WARN[0;39m] [35m2344[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.basic.dao.ILogDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:32:05.905[0;39m [[33m WARN[0;39m] [35m2344[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.toolkit.ReflectionKit[0;39m:107 [2m:[0;39m Warn: CityBizImpl's superclass not ParameterizedType
[2m2022-04-08 15:32:05.905[0;39m [[33m WARN[0;39m] [35m2344[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.toolkit.ReflectionKit[0;39m:107 [2m:[0;39m Warn: CityBizImpl's superclass not ParameterizedType
[2m2022-04-08 15:32:06.135[0;39m [[33m WARN[0;39m] [35m2344[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.basic.dao.IRoleDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:32:06.439[0;39m [[33m WARN[0;39m] [35m2344[0;39m [2m[           main ][0;39m [33mnet.sf.ehcache.config.ConfigurationFactory[0;39m:136 [2m:[0;39m No configuration found. Configuring ehcache from ehcache-failsafe.xml  found in the classpath: jar:file:/D:/2022/maven_repos/net/sf/ehcache/ehcache/2.10.9.2/ehcache-2.10.9.2.jar!/ehcache-failsafe.xml
[2m2022-04-08 15:32:06.560[0;39m [[33m WARN[0;39m] [35m2344[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.mdiy.dao.ITagDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:32:06.775[0;39m [[33m WARN[0;39m] [35m2344[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.toolkit.ReflectionKit[0;39m:107 [2m:[0;39m Warn: ModelDataImpl's superclass not ParameterizedType
[2m2022-04-08 15:32:06.776[0;39m [[33m WARN[0;39m] [35m2344[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.toolkit.ReflectionKit[0;39m:107 [2m:[0;39m Warn: ModelDataImpl's superclass not ParameterizedType
[2m2022-04-08 15:32:07.010[0;39m [[33m WARN[0;39m] [35m2344[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.mdiy.dao.IDictDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:32:10.489[0;39m [[32m INFO[0;39m] [35m2344[0;39m [2m[           main ][0;39m [32morg.quartz.impl.StdSchedulerFactory[0;39m:1220 [2m:[0;39m Using default implementation for ThreadExecutor
[2m2022-04-08 15:32:10.501[0;39m [[32m INFO[0;39m] [35m2344[0;39m [2m[           main ][0;39m [32morg.quartz.core.SchedulerSignalerImpl[0;39m:61 [2m:[0;39m Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
[2m2022-04-08 15:32:10.501[0;39m [[32m INFO[0;39m] [35m2344[0;39m [2m[           main ][0;39m [32morg.quartz.core.QuartzScheduler[0;39m:229 [2m:[0;39m Quartz Scheduler v.2.3.2 created.
[2m2022-04-08 15:32:10.502[0;39m [[32m INFO[0;39m] [35m2344[0;39m [2m[           main ][0;39m [32morg.quartz.simpl.RAMJobStore[0;39m:155 [2m:[0;39m RAMJobStore initialized.
[2m2022-04-08 15:32:10.503[0;39m [[32m INFO[0;39m] [35m2344[0;39m [2m[           main ][0;39m [32morg.quartz.core.QuartzScheduler[0;39m:294 [2m:[0;39m Scheduler meta-data: Quartz Scheduler (v2.3.2) 'quartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

[2m2022-04-08 15:32:10.503[0;39m [[32m INFO[0;39m] [35m2344[0;39m [2m[           main ][0;39m [32morg.quartz.impl.StdSchedulerFactory[0;39m:1374 [2m:[0;39m Quartz scheduler 'quartzScheduler' initialized from an externally provided properties instance.
[2m2022-04-08 15:32:10.503[0;39m [[32m INFO[0;39m] [35m2344[0;39m [2m[           main ][0;39m [32morg.quartz.impl.StdSchedulerFactory[0;39m:1378 [2m:[0;39m Quartz scheduler version: 2.3.2
[2m2022-04-08 15:32:10.503[0;39m [[32m INFO[0;39m] [35m2344[0;39m [2m[           main ][0;39m [32morg.quartz.core.QuartzScheduler[0;39m:2293 [2m:[0;39m JobFactory set to: org.springframework.scheduling.quartz.SpringBeanJobFactory@2e53f980
[2m2022-04-08 15:32:10.688[0;39m [[32m INFO[0;39m] [35m2344[0;39m [2m[           main ][0;39m [32morg.apache.coyote.http11.Http11NioProtocol[0;39m:173 [2m:[0;39m Starting ProtocolHandler ["http-nio-8080"]
[2m2022-04-08 15:32:10.706[0;39m [[32m INFO[0;39m] [35m2344[0;39m [2m[           main ][0;39m [32morg.quartz.core.QuartzScheduler[0;39m:547 [2m:[0;39m Scheduler quartzScheduler_$_NON_CLUSTERED started.
[2m2022-04-08 15:32:10.719[0;39m [[32m INFO[0;39m] [35m2344[0;39m [2m[           main ][0;39m [32mnet.mingsoft.MSApplication[0;39m:61 [2m:[0;39m Started MSApplication in 12.389 seconds (JVM running for 14.794)
[2m2022-04-08 15:32:50.127[0;39m [[32m INFO[0;39m] [35m2344[0;39m [2m[nio-8080-exec-2 ][0;39m [32morg.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/][0;39m:173 [2m:[0;39m Initializing Spring DispatcherServlet 'dispatcherServlet'
[2m2022-04-08 15:33:40.627[0;39m [[32m INFO[0;39m] [35m19536[0;39m [2m[           main ][0;39m [32mnet.mingsoft.MSApplication[0;39m:55 [2m:[0;39m Starting MSApplication on yb with PID 19536 (D:\aa\MCMS-master\MCMS-master\target\classes started by Administrator in D:\aa\MCMS-master\MCMS-master)
[2m2022-04-08 15:33:40.637[0;39m [[32m INFO[0;39m] [35m19536[0;39m [2m[           main ][0;39m [32mnet.mingsoft.MSApplication[0;39m:652 [2m:[0;39m The following profiles are active: dev
[2m2022-04-08 15:33:43.125[0;39m [[32m INFO[0;39m] [35m19536[0;39m [2m[           main ][0;39m [32mcom.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure[0;39m:56 [2m:[0;39m Init DruidDataSource
[2m2022-04-08 15:33:43.234[0;39m [[32m INFO[0;39m] [35m19536[0;39m [2m[           main ][0;39m [32mcom.alibaba.druid.pool.DruidDataSource[0;39m:998 [2m:[0;39m {dataSource-1} inited
[2m2022-04-08 15:33:44.075[0;39m [[33m WARN[0;39m] [35m19536[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.basic.dao.IManagerDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:33:44.213[0;39m [[33m WARN[0;39m] [35m19536[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.basic.dao.IModelDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:33:44.260[0;39m [[33m WARN[0;39m] [35m19536[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.metadata.TableInfoHelper[0;39m:307 [2m:[0;39m Can not find table primary key in Class: "net.mingsoft.basic.entity.RoleModelEntity".
[2m2022-04-08 15:33:45.183[0;39m [[32m INFO[0;39m] [35m19536[0;39m [2m[           main ][0;39m [32morg.apache.coyote.http11.Http11NioProtocol[0;39m:173 [2m:[0;39m Initializing ProtocolHandler ["http-nio-8080"]
[2m2022-04-08 15:33:45.183[0;39m [[32m INFO[0;39m] [35m19536[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.StandardService[0;39m:173 [2m:[0;39m Starting service [Tomcat]
[2m2022-04-08 15:33:45.184[0;39m [[32m INFO[0;39m] [35m19536[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.StandardEngine[0;39m:173 [2m:[0;39m Starting Servlet engine: [Apache Tomcat/9.0.46]
[2m2022-04-08 15:33:45.187[0;39m [[32m INFO[0;39m] [35m19536[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.AprLifecycleListener[0;39m:173 [2m:[0;39m Loaded Apache Tomcat Native library [1.2.31] using APR version [1.7.0].
[2m2022-04-08 15:33:45.187[0;39m [[32m INFO[0;39m] [35m19536[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.AprLifecycleListener[0;39m:173 [2m:[0;39m APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
[2m2022-04-08 15:33:45.188[0;39m [[32m INFO[0;39m] [35m19536[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.AprLifecycleListener[0;39m:173 [2m:[0;39m APR/OpenSSL configuration: useAprConnector [false], useOpenSSL [true]
[2m2022-04-08 15:33:45.191[0;39m [[32m INFO[0;39m] [35m19536[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.AprLifecycleListener[0;39m:173 [2m:[0;39m OpenSSL successfully initialized [OpenSSL 1.1.1l  24 Aug 2021]
[2m2022-04-08 15:33:45.358[0;39m [[32m INFO[0;39m] [35m19536[0;39m [2m[           main ][0;39m [32morg.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/][0;39m:173 [2m:[0;39m Initializing Spring embedded WebApplicationContext
[2m2022-04-08 15:33:45.834[0;39m [[33m WARN[0;39m] [35m19536[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.cms.dao.ICategoryDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:33:45.897[0;39m [[33m WARN[0;39m] [35m19536[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.cms.dao.IContentDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:33:46.166[0;39m [[33m WARN[0;39m] [35m19536[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.mdiy.dao.IModelDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:33:46.805[0;39m [[33m WARN[0;39m] [35m19536[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.toolkit.ReflectionKit[0;39m:107 [2m:[0;39m Warn: HistoryLogBizImpl's superclass not ParameterizedType
[2m2022-04-08 15:33:46.805[0;39m [[33m WARN[0;39m] [35m19536[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.toolkit.ReflectionKit[0;39m:107 [2m:[0;39m Warn: HistoryLogBizImpl's superclass not ParameterizedType
[2m2022-04-08 15:33:47.063[0;39m [[33m WARN[0;39m] [35m19536[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.mdiy.dao.IPageDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:33:47.598[0;39m [[33m WARN[0;39m] [35m19536[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.basic.dao.ILogDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:33:47.847[0;39m [[33m WARN[0;39m] [35m19536[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.toolkit.ReflectionKit[0;39m:107 [2m:[0;39m Warn: CityBizImpl's superclass not ParameterizedType
[2m2022-04-08 15:33:47.848[0;39m [[33m WARN[0;39m] [35m19536[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.toolkit.ReflectionKit[0;39m:107 [2m:[0;39m Warn: CityBizImpl's superclass not ParameterizedType
[2m2022-04-08 15:33:48.081[0;39m [[33m WARN[0;39m] [35m19536[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.basic.dao.IRoleDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:33:48.397[0;39m [[33m WARN[0;39m] [35m19536[0;39m [2m[           main ][0;39m [33mnet.sf.ehcache.config.ConfigurationFactory[0;39m:136 [2m:[0;39m No configuration found. Configuring ehcache from ehcache-failsafe.xml  found in the classpath: jar:file:/D:/2022/maven_repos/net/sf/ehcache/ehcache/2.10.9.2/ehcache-2.10.9.2.jar!/ehcache-failsafe.xml
[2m2022-04-08 15:33:48.538[0;39m [[33m WARN[0;39m] [35m19536[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.mdiy.dao.ITagDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:33:48.746[0;39m [[33m WARN[0;39m] [35m19536[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.toolkit.ReflectionKit[0;39m:107 [2m:[0;39m Warn: ModelDataImpl's superclass not ParameterizedType
[2m2022-04-08 15:33:48.747[0;39m [[33m WARN[0;39m] [35m19536[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.toolkit.ReflectionKit[0;39m:107 [2m:[0;39m Warn: ModelDataImpl's superclass not ParameterizedType
[2m2022-04-08 15:33:49.030[0;39m [[33m WARN[0;39m] [35m19536[0;39m [2m[           main ][0;39m [33mcom.baomidou.mybatisplus.core.injector.AbstractMethod[0;39m:323 [2m:[0;39m [net.mingsoft.mdiy.dao.IDictDao.delete] Has been loaded by XML or SqlProvider or Mybatis's Annotation, so ignoring this injection for [class com.baomidou.mybatisplus.core.injector.methods.Delete]
[2m2022-04-08 15:33:52.849[0;39m [[32m INFO[0;39m] [35m19536[0;39m [2m[           main ][0;39m [32morg.quartz.impl.StdSchedulerFactory[0;39m:1220 [2m:[0;39m Using default implementation for ThreadExecutor
[2m2022-04-08 15:33:52.865[0;39m [[32m INFO[0;39m] [35m19536[0;39m [2m[           main ][0;39m [32morg.quartz.core.SchedulerSignalerImpl[0;39m:61 [2m:[0;39m Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
[2m2022-04-08 15:33:52.865[0;39m [[32m INFO[0;39m] [35m19536[0;39m [2m[           main ][0;39m [32morg.quartz.core.QuartzScheduler[0;39m:229 [2m:[0;39m Quartz Scheduler v.2.3.2 created.
[2m2022-04-08 15:33:52.866[0;39m [[32m INFO[0;39m] [35m19536[0;39m [2m[           main ][0;39m [32morg.quartz.simpl.RAMJobStore[0;39m:155 [2m:[0;39m RAMJobStore initialized.
[2m2022-04-08 15:33:52.867[0;39m [[32m INFO[0;39m] [35m19536[0;39m [2m[           main ][0;39m [32morg.quartz.core.QuartzScheduler[0;39m:294 [2m:[0;39m Scheduler meta-data: Quartz Scheduler (v2.3.2) 'quartzScheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

[2m2022-04-08 15:33:52.867[0;39m [[32m INFO[0;39m] [35m19536[0;39m [2m[           main ][0;39m [32morg.quartz.impl.StdSchedulerFactory[0;39m:1374 [2m:[0;39m Quartz scheduler 'quartzScheduler' initialized from an externally provided properties instance.
[2m2022-04-08 15:33:52.868[0;39m [[32m INFO[0;39m] [35m19536[0;39m [2m[           main ][0;39m [32morg.quartz.impl.StdSchedulerFactory[0;39m:1378 [2m:[0;39m Quartz scheduler version: 2.3.2
[2m2022-04-08 15:33:52.868[0;39m [[32m INFO[0;39m] [35m19536[0;39m [2m[           main ][0;39m [32morg.quartz.core.QuartzScheduler[0;39m:2293 [2m:[0;39m JobFactory set to: org.springframework.scheduling.quartz.SpringBeanJobFactory@d4f2f3d
[2m2022-04-08 15:33:53.081[0;39m [[32m INFO[0;39m] [35m19536[0;39m [2m[           main ][0;39m [32morg.apache.coyote.http11.Http11NioProtocol[0;39m:173 [2m:[0;39m Starting ProtocolHandler ["http-nio-8080"]
[2m2022-04-08 15:33:53.105[0;39m [[32m INFO[0;39m] [35m19536[0;39m [2m[           main ][0;39m [32morg.quartz.core.QuartzScheduler[0;39m:547 [2m:[0;39m Scheduler quartzScheduler_$_NON_CLUSTERED started.
[2m2022-04-08 15:33:53.117[0;39m [[32m INFO[0;39m] [35m19536[0;39m [2m[           main ][0;39m [32mnet.mingsoft.MSApplication[0;39m:61 [2m:[0;39m Started MSApplication in 13.143 seconds (JVM running for 15.495)
[2m2022-04-08 15:34:59.439[0;39m [[32m INFO[0;39m] [35m19536[0;39m [2m[nio-8080-exec-1 ][0;39m [32morg.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/][0;39m:173 [2m:[0;39m Initializing Spring DispatcherServlet 'dispatcherServlet'
[2m2022-04-08 15:39:47.756[0;39m [[33m WARN[0;39m] [35m19536[0;39m [2m[nio-8080-exec-2 ][0;39m [33morg.apache.catalina.util.SessionIdGeneratorBase[0;39m:173 [2m:[0;39m Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [340] milliseconds.
[2m2022-04-08 15:44:38.450[0;39m [[33m WARN[0;39m] [35m19536[0;39m [2m[io-8080-exec-10 ][0;39m [33morg.apache.ibatis.io.SerialFilterChecker[0;39m:46 [2m:[0;39m As you are using functionality that deserializes object streams, it is recommended to define the JEP-290 serial filter. Please refer to https://docs.oracle.com/pls/topic/lookup?ctx=javase15&id=GUID-8296D8E8-2B93-4B9A-856E-0A65AF9B8C66
